version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/opt/app
    depends_on:
     - "redis"
  redis:
    image: "redis:alpine"
networks:
  redis:
    driver: bridge